language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE sendit;" -U postgres
addons:
  - postgres: ""
script:
  - coveralls
  - coverage
  - pytest --cov=sendapi/
after_script:
  -coveralls
  
